### ISSUE TITLE
api section

### ISSUE THREAD

**Issue by yoshuawuyts** [wercker/docs#133]
[TBI]

**Comment by hatchan** [comment]
A new section should be added besides `Learn` and `Docs` called API.

This section should looks the same as `Docs`. Where the left side will contain the endpoints, and will navigate to the endpoint details.

These details may contain the following:

- URL signature (HTTP method, url route)
- Small description (markdown)
- Input parameters:
  - Query string parameters
  - Body parameters
- Example response payload
