### ISSUE TITLE
api content

### ISSUE THREAD

**Issue by yoshuawuyts** [wercker/docs#141]
We need to fill it up since the `api_docs` is already live; I suggest starting with the `v3` api endpoints since these are considered public.
- [x] `api-routes` - not a strict `api-*` module, doesn't expose any endpoints
- [x] `api-deploys` - https://github.com/wercker/docs/pull/144
- [x] `api-applications`  - https://github.com/wercker/docs/pull/145
- [x] `api-steps` - https://github.com/wercker/docs/pull/146
- [x] `api-builds` - https://github.com/wercker/docs/pull/143
- [ ] `api-tokens`

### See Also
- [api v3 search on wercker/wercker](https://github.com/wercker/wercker/search?p=1&q=v3&utf8=%E2%9C%93)

**Comment by yoshuawuyts** [comment]
@hatchan I'm not entirely sure how we're using `api-tokens`. Could you maybe explain a little? I'd be happy to create the last docs PR for them once I understand them a bit better, though if you want to you're also welcome to. Thanks! :smile:

**Comment by hatchan** [comment]
With the token endpoints you'll be able to manage access tokens to the wercker API. With one such token you can authenticate to the API.

Currently the feature is hidden behind the `rodekool` feature flag. 

Eventually all our own applications need to use this endpoint to generate a token (desktop, sentcli, etc)

**Comment by lindseybateman** [comment]
is this issue in progress or finished?

**Comment by yoshuawuyts** [comment]
These endpoints are currently documented: http://devcenter.wercker.com/api/endpoints/index.html. I think it's best to create a new issue for this.
