### ISSUE TITLE
Document prefixing env vars with X_ when using the sentcli environment

### ISSUE THREAD

**Issue by mwhooker** [wercker/docs#148]
Users can set env vars in an environment file which they can pass in with `--environment`.

Only those variables starting with `X_` will pass through to the steps. Let's document this process.

**Comment by hatchan** [comment]
Was running into this as well. 

But I was thinking that maybe it is a better idea to import the env vars in that file as-is. Opinions?

**Comment by hatchan** [comment]
See: wercker/support#21

**Comment by christophercurrie** [comment]
This issue was closed without action or comment. The docs for environments are still unclear. Is there a plan for future action?

**Comment by mwhooker** [comment]
@christophercurrie agreed that we still need to come up with a more user-friendly solution. However, we've documented it here http://devcenter.wercker.com/docs/environment-variables/local-env-vars.html and would love some feedback if it's still unclear.
Thanks!

**Comment by christophercurrie** [comment]
It's clear enough now that I find it, but I would have expected a mention somewhere in the "using the cli" section. A pointer to this other page would be enough, and super helpful. Thanks!

**Comment by mwhooker** [comment]
@christophercurrie good point. I think I'll try to get that section moved under "using the cli" instead of under "environmental variables". thanks for the feedback!

**Comment by schmengler** [comment]
If anybody else came here looking for this documentation, the current link is: http://devcenter.wercker.com/cli/configuration/environment-variables.html
