### ISSUE TITLE
new s3 redirects aren't working & not throwing error on fail

### ISSUE THREAD

**Issue by yoshuawuyts** [wercker/docs#164]
the redirect routes added in https://github.com/wercker/docs/commit/422fb0f5adef1599e97241bad9bd18856e637870 aren't working. It appears we're not throwing an error if the redirects fail as seen in https://app.wercker.com/#deploystep/5559b319676bb8c31f53a81e

### todo
- [x] fix redirects (use http / https)
- [x] make errors in the redirect script exit the process with statuscode 1 so the deploy fails properly

### See Also
- [tweet issue report](https://twitter.com/nhuray/status/600640600904306688)

**Comment by hatchan** [comment]
Prefix with a `/` that's all :)
