### ISSUE TITLE
Wrong link to learn section on devcenter

### ISSUE THREAD

**Issue by Tonnu** [wercker/docs#174]
http://devcenter.wercker.com/docs/index.html contains a link to the learn section: http://devcenter.wercker.com/learn/basics/01_introduction.html which 404's

It should be http://devcenter.wercker.com/learn/basics/introduction.html

**Comment by mies** [comment]
@Tonnu this should be fixed in: https://github.com/wercker/docs/pull/172

at least I don't get any search results in the repo on "http://devcenter.wercker.com/learn/basics/01_introduction.html"

**Comment by hatchan** [comment]
The links should have redirected to the correct link though :-/

**Comment by hatchan** [comment]
See #166

**Comment by hatchan** [comment]
Aah I see, #166 has the incorrect URL's :crying_cat_face:

**Comment by hatchan** [comment]
Redirect url is now in place (solved by #175)
