### ISSUE TITLE
Pricing?

### ISSUE THREAD

**Issue by k-j-kleist** [wercker/docs#177]
"Free account" - fine. But there is still no such a thing as a free lunch... So when will you tell us about your upcoming pricing policy?

**Comment by ALenfant** [comment]
Yes, I agree relying on your service while your pricing isn't clear is a big problem for me. You really should clarify this.

**Comment by artemave** [comment]
+1

**Comment by Machiel** [comment]
+1

**Comment by agauniyal** [comment]
+1

**Comment by robzienert** [comment]
+1
