### ISSUE TITLE
code highlighting does some weird things sometimes

### ISSUE THREAD

**Issue by mies** [wercker/docs#238]
see screenshot
![screen shot 2015-06-26 at 10 14 32](https://cloud.githubusercontent.com/assets/19435/8383060/2b112168-1bec-11e5-845d-5ed046f551da.png)

**Comment by flenter** [comment]
A workaround is to add no-highlight after the 3 `

**Comment by mies** [comment]
good to know, might be an idea to go through some of the docs and fix it. but requires some time. closing
