### ISSUE TITLE
Learn section images are not scaling correctly

### ISSUE THREAD

**Issue by Tonnu** [wercker/docs#272]
The images in the learn section appear to be too big and do not fit the screen (even if expanded fully).

![screen shot 2015-08-31 at 14 45 21](https://cloud.githubusercontent.com/assets/1899787/9578979/ece5252e-4fee-11e5-9607-4d04020776f4.png)

**Comment by lindseybateman** [comment]
thanks, working on the same bug in docs and api

**Comment by lindseybateman** [comment]
fix the bug
