### ISSUE TITLE
Inline images in "Learn" broken in Firefox

### ISSUE THREAD

**Issue by mmwtsn** [wercker/docs#279]
When browsing around the "Learn" section of the documentation I noticed that inline image widths are not being constrained in Firefox. This breaking the layout:

![extra-wide](https://cloud.githubusercontent.com/assets/1479130/9852106/640e64ae-5aca-11e5-9ea1-28ff96fc7cbc.png)

It looks like the viewport width setting on the image is being ignored:

![ignored](https://cloud.githubusercontent.com/assets/1479130/9852164/b50d8150-5aca-11e5-8ff5-3ebfacdbcfac.png)

I threw an `!important` in on that line to see if it's a cascade/specificity issue or if the value is being ignored. Firefox respected the `90vw` width (which makes sense because [it should be supported](http://caniuse.com/#search=vw)) but the layout issue was not resolved. Not sure what's going on there.

Tested with v40.0.3 on OS X. Looks good in Chrome.

**Comment by lindseybateman** [comment]
Thanks for reporting and the insights, we deployed a fix.

**Comment by mmwtsn** [comment]
Looks good! Thanks for the quick response.
