### ISSUE TITLE
List of current services

### ISSUE THREAD

**Issue by westonplatter** [wercker/docs#324]
I love the example on the main services page showing how to use mongo and redis [here](http://devcenter.wercker.com/docs/services/index.html).

Do you have a list of currently available services? Or may there's another way that I would know about how to use `memcache` in my testing env.

**Comment by Tonnu** [comment]
You can use any docker container as a service. If you would like to use memcache, check out the official image here: https://hub.docker.com/_/memcached/

You can then use it as you would with mongo or redis:

```
box: yourbox
services:
    - memcached
```

**Comment by westonplatter** [comment]
@Tonnu gotchya. Thanks!
