### ISSUE TITLE
push docker image to aws ecr using wercker

### ISSUE THREAD

**Issue by shantanupanda** [wercker/docs#325]
Hi,

I have a repo created on aws ecr, i am trying to push my build image to it using the following steps:

http://devcenter.wercker.com/docs/containers/pushing-containers.html#hub

for private repo.
getting 404 error.

Please help.

**Comment by Tonnu** [comment]
Hi, we're currently working on supporting ECR. Can't give you an exact date, but we should be able to merge it in somewhere in the coming weeks.

**Comment by AndreCapelache** [comment]
+1

**Comment by fugufish** [comment]
+ 1

**Comment by snikch** [comment]
Sorry to add to the noise, but I'm following this issue as well and am keen on ECR support asap.

**Comment by pedrocalgaro** [comment]
+ 1

**Comment by faiq** [comment]
see https://github.com/wercker/wercker/issues/58 for updates on this.

this is also not a documentation issue, so i'm going to close
