### ISSUE TITLE
rabbitmq page is empty

### ISSUE THREAD

**Issue by flenter** [wercker/docs#332]
Url: http://devcenter.wercker.com/docs/services/rabbitmq.html

It's not in the menu but still got indexed by google.

**Comment by flenter** [comment]
Why is this issue closed? The html still exists and googling for wercker and rabbitmq it is (for me) the 2nd result

**Comment by olebedev** [comment]
Hi @flenter,

this helps to me:
```go
var rabbitmq = "amqp://guest:guest@localhost:5672"

func init() {
	if addr, ok := os.LookupEnv("RABBITMQ_PORT_5672_TCP_ADDR"); ok {
		r, _ := url.Parse(rabbitmq)
		r.Host = addr + ":5672"
		rabbitmq = r.String()
	}
}
```
