### ISSUE TITLE
docker-compose support

### ISSUE THREAD

**Issue by shehi** [wercker/docs#378]
Is docker-compose supported in Wercker? Couldn't find anything in docs in this regard.

**Comment by Tonnu** [comment]
We don't support Docker compose right now. We do have our own syntax that allows you to spin up services pretty easily. Check out http://devcenter.wercker.com/docs/services/index.html and http://devcenter.wercker.com/docs/services/advanced-services.html#local-services if you want to reference projects that you have on-disk as service.

**Comment by faiq** [comment]
@shehi we are considering adding support for docker compose. if you're interested in following along, we have an open issue for it in the cli. we would love to hear what you have to say!

https://github.com/wercker/wercker/issues/63

**Comment by shehi** [comment]
@faiq Thanks.
@Tonnu If I started to learn every single vendor's own non-standard syntaxes, life of mine would become unbearable. No thanks.

**Comment by lukeaus** [comment]
+1
