### ISSUE TITLE
Devcenter currently downloads a 1.6 MB file "build.js"

### ISSUE THREAD

**Issue by hatchan** [wercker/docs#78]
It looks like this file contains unminified Javscript. It also contains a massive sourceMappingURL blob at the end of the file.

**Comment by yoshuawuyts** [comment]
Currently the artifact is 857.2kb, of which react is 510.4kb. Since we're already sitting under the 1mb threshold, I think it's safe to close this issue for now. Also fun to note: our repo-specific code is about 23kb. Data extracted with [disc](https://github.com/hughsk/disc).

**Comment by mwhooker** [comment]
is it minified or no?

if no we should create a separate issue to minify it

**Comment by mwhooker** [comment]
react is only  120kb minfied https://fbcdn-dragon-a.akamaihd.net/hphotos-ak-xap1/t39.3284-6/11057094_955943151112476_1299188456_n.js

so I would assume it's not.

**Comment by yoshuawuyts** [comment]
we're currently not minifying. Good one.

![screen shot 2015-04-29 at 18 02 30](https://cloud.githubusercontent.com/assets/2467194/7404589/05d444ea-ee9a-11e4-8dae-640d6fd8b97b.png)

**Comment by hatchan** [comment]
I implemented minification a few weeks ago, these changes must have been
lost in a merge :-/
On Apr 30, 2015 3:03 AM,
"Y̬̯͖̭̗͇͈͙͙̖̥͒͋ͥͭ̏͒͛͞ô̹̗̞͈͓̥̒͆͆͑̏ͫͪͤͥͧ̀͒̀s͉̦̘̘̪̱͉̰̦̓̆ͯͤͪ͒ͭ͑̈͘h̨̤̫͉̋͊͂͌͐ͣ̋̓͌̒͂͐͒̆ͅu̮̒́ͮ̓͋̐ͫ͒̓̍ͬͬ̑ͤ̈ͤͧ͘a͕̻̻̠̲͙͋̌̔̒̒ͩ́ͭ̊́̂͗͠
̛̬̞̲͕̭̤͕̄͒̐̐̂̋̃̎̍ͦ̿W̗̤̜̜ͪ̐͂̆ͪ̀ͧ̌ͥ̅ͭ̓̚͝ͅu̧̱̦̣͍̇ͨͪ̎͒͋̈ͭ̓̃̽ͬͪ̚y̔̑̋͗̐̽ͦ͂̐̈͋ͣ́ͧ͋̃ͥ̚͘t̖̭̼̩̝̺̞̜̬͍̩̏ͦ͛́̑̇̚͞s̒̏̏̀̃̂̿ͯ͛͒ͩ̄̂ͯ̆̌ͮ̒ͭ"

**Comment by yoshuawuyts** [comment]
@hatchan minification is in there, no worries.
