### ISSUE TITLE
Top bar navigation hijacks ctrl + click or middle mouse click

### ISSUE THREAD

**Issue by hatchan** [wercker/docs#82]
For some reason the links in the top bar navigation (Learn, Docs, etc) hijack ctrl + click and middle mouse click and open the link in the current window. 

Normal behavior is opening the link in a new tab.

**Comment by piotrpalek** [comment]
Confirming, this is annoying..

**Comment by yoshuawuyts** [comment]
Whoops, that's not good. Will investigate this tomorrow morning (CET).

**Comment by yoshuawuyts** [comment]
Found the culprit, https://github.com/wercker/docs/blob/master/docs-nav/index.js#L106-L118. Since we're just dealing with static html this can be safely removed.
